//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace natural_medicine.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class import
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public Nullable<byte> publisher_id { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<System.DateTime> import_date { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public string note { get; set; }
    
        public virtual product product { get; set; }
        public virtual publisher publisher { get; set; }
    }
}
