//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace natural_medicine.Models
{
    using System;
    using System.Collections.Generic;
    using System.Web.Mvc;

    public partial class news
    {
        public int id { get; set; }
        public string title { get; set; }
        [AllowHtml]
        public string content { get; set; }
        public Nullable<System.DateTime> date_post { get; set; }
        public Nullable<System.DateTime> create_at { get; set; }
        public Nullable<System.DateTime> update_at { get; set; }
    }
}
